### ISSUE TITLE
can not retry select for update statement

### ISSUE THREAD

**Issue by ShiYour** [MeetYouDevs/big-whale#72]
启动时，就有job报这个，怎么判断哪里出现了问题

2021-12-17 18:18:33.305 ERROR  (QuartzScheduler.java:2401)- An error occurred while firing triggers '[Trigger 'DEFAULT.6da64b5bd2ee-babeea54-29a6-4c27-9a4e-9248d97a18e0':  triggerClass: 'org.quartz.impl.triggers.CronTriggerImpl calendar: 'null' misfireInstruction: 2 nextFireTime: Fri Dec 17 18:16:50 CST 2021]'
org.quartz.JobPersistenceException: Couldn't commit jdbc connection. [1008803] can not retry select for update statement
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.commitConnection(JobStoreSupport.java:3734)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.executeInNonManagedTXLock(JobStoreSupport.java:3851)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.triggersFired(JobStoreSupport.java:2962)
	at org.quartz.core.QuartzSchedulerThread.run(QuartzSchedulerThread.java:353)
Caused by: java.sql.SQLException: [1008803] can not retry select for update statement
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:963)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3966)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3902)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2526)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2673)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2545)
	at com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1614)
	at com.zaxxer.hikari.pool.ProxyConnection.commit(ProxyConnection.java:368)
	at com.zaxxer.hikari.pool.HikariProxyConnection.commit(HikariProxyConnection.java)
	at sun.reflect.GeneratedMethodAccessor132.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.quartz.impl.jdbcjobstore.AttributeRestoringConnectionInvocationHandler.invoke(AttributeRestoringConnectionInvocationHandler.java:73)
	at com.sun.proxy.$Proxy116.commit(Unknown Source)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.commitConnection(JobStoreSupport.java:3732)
	... 3 common frames omitted

**Comment by ShiYour** [comment]
数据库初始化在了tidb，默认乐观锁导致。设置成悲观锁ok。
